name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
        mysql:
          image: mysql:5.7
          env:
            MY_SQL_ROOT_PASSWORD: root
            MYSQL_DATABASE : free_shark
          ports:
            - 3306
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Check mysql
      run: | 
        mysql -uroot -proot --init-command="CREATE DATABASE IF NOT EXISTS free_shark"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: config envvar
      run: |
        export FLASK_APP=free_shark
        export FLASK_ENV=development 
        flask init-db
      env:
        DB_HOST: localhost
        DB_USER: root
        DB_PASSWORD: root
        DB_PORT: 3306
        DB_CHARSET: utf8
        DATABASE: free_shark
        FLASK_APP: free_shark
        FLASK_ENV: development
      
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov codecov
        pytest --cov=free_shark --cov-report=xml tests
      env:
        DB_HOST: localhost
        DB_USER: root
        DB_PASSWORD: root
        DB_PORT: 3306
        DB_CHARSET: utf8
        DATABASE: free_shark
        FLASK_APP: free_shark
        FLASK_ENV: development

    - name: Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        # User defined upload name. Visible in Codecov UI
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.xml
        

